# Generated by Django 2.1.2 on 2018-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181126_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=8)),
                ('avatar', models.FileField(upload_to='website/media/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
