# Generated by Django 2.1.2 on 2018-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181205_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idinfo',
            name='avatar',
            field=models.FileField(upload_to='avatars'),
        ),
    ]
